### ISSUE TITLE
The site lags extremely hard when scrolling rapidly

### ISSUE THREAD

**Issue by thekoksus** [ChatterBoxGames/CBGCommunityWebsite#4]
**Extreme lag when scrolling on the site.**

**Scrolling causes CPU ussage to go up to 100% on 3 cores**

**System information:**

*Operating system:* `Ubuntu 16.04`

*Browser:* `Chromium 62`

*CPU:* `AMD FX 6300`

*GPU:* `nVidia GTX 1050 Ti`

**What can cause the issue:**

I belive the `filter: brightness(50%) blur(0.75em);` attribute on `#hero-main` causes the issue as disabling it in dev tools made the lag invisible

**Comment by theLMGN** [comment]
Browser issue. Report it to @chromium

**Comment by thekoksus** [comment]
@theLMGN well still. Maybe the background should be optional? Or you could pre-fade the image in Photoshop / GIMP ? That site lags mobile clients no matter the browser...
